### PR TITLE
docstring documentation for client + mixins

### PR DESCRIPTION
**Pull request by omernestor**

### CODE REVIEW

**Comment by giladneural** [comment]
test this please

**Comment by giladneural** [comment]
test this please

**Comment by giladneural** [comment]
test this please

**Comment by giladneural** [comment]
test this please

**Comment by giladneural** [comment]
test this please

**Comment by giladneural** [comment]
test this please

**Comment by glebzh** [comment]
test this please

**Comment by glebzh** [comment]
test this please

**Pull request merged**
